### ISSUE TITLE
change background color by button

### ISSUE THREAD

**Issue by iGhoneim** [PUASummerOfCode/Clickable#2]
I wish if we could change this RED background color to BLUE by clicking on new Button, can we?

**Comment by computeristgeek** [comment]
I want this feature too!

**Comment by garo50** [comment]
i could do it, but if so that will change the project settings(gradle path).

**Comment by iGhoneim** [comment]
could do it = assign yourself , start working , commit & push 📦

**Comment by iGhoneim** [comment]
thank you, really I appreciate your efforts 👍

**Comment by computeristgeek** [comment]
closed by @garo50 's e092290e5065d45926ea42ff690adf225f175e97
